### ISSUE TITLE
sonar docker方式安装之后，安装插件，重启sonar，还是英文

### ISSUE THREAD

**Issue by woxiangbo** [xuhuisheng/sonar-l10n-zh#42]
你好，我通过docker安装的sonar，登录sonar 找到插件，安装完成，sonar提示需要重启，重启完之后，还是英文，请问这种情况怎么解决呢？万分感谢！

**Comment by woxiangbo** [comment]
![image](https://user-images.githubusercontent.com/3446874/109485189-57c68380-7abc-11eb-95ef-75481f564d7c.png)

**Comment by xuhuisheng** [comment]
浏览器语言是中文，就能显示中文了

**Comment by ontheway01** [comment]
> 浏览器语言是中文，就能显示中文了

Me too，我之前遇到也是这样问题。选择chrome浏览器，在设置中语言选择中文（简体）即可。

**Comment by xuhuisheng** [comment]
超过5个月没有更新，先关闭了。
