### ISSUE TITLE
怎么获取历史版本的jar包

### ISSUE THREAD

**Issue by anxiuze** [xuhuisheng/sonar-l10n-zh#46]
你好，怎么获取历史版本的jar包啊？最新的版本不能兼容老版本的sonarqube

**Comment by xuhuisheng** [comment]
原则上用sonarqube的应用市场，会自动匹配对应的插件版本。

然后，项目首页维护了一个兼容版本矩阵，也可以自己手工下载对应的版本放到extensions/plugin目录下，重启就可以用。

**Comment by xuhuisheng** [comment]
超过一个月没有更新，我先关闭了。如果有问题可以再打开。
