### ISSUE TITLE
你好我是7.7版本。但是放进去之后，系统就跑不起来了。

### ISSUE THREAD

**Issue by eric-5512** [xuhuisheng/sonar-l10n-zh#47]

**Comment by xuhuisheng** [comment]
SonarQube-7.7对应1.27 https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-1.27/sonar-l10n-zh-plugin-1.27.jar

而且汉化包不应该影响系统运行呀，看看后台有啥报错。

**Comment by eric-5512** [comment]
> SonarQube-7.7对应1.27 https://github.com/xuhuisheng/sonar-l10n-zh/releases/download/sonar-l10n-zh-plugin-1.27/sonar-l10n-zh-plugin-1.27.jar
> 
> 而且汉化包不应该影响系统运行呀，看看后台有啥报错。

稍等，我看看。谢谢！！！

**Comment by eric-5512** [comment]
好用了，谢谢。我是在github上下载的。。但是不好用。
