### ISSUE TITLE
Version 9.0.1 (build 46107) 无法通过9.0版本的插件进行汉化

### ISSUE THREAD

**Issue by zhenyu-lan** [xuhuisheng/sonar-l10n-zh#48]
![image](https://user-images.githubusercontent.com/62124738/130194475-02de110a-058a-4c8e-8f4e-1363eb85107d.png)
如果方便请更新插件版本；

**Comment by xuhuisheng** [comment]
看截图是安装成功了，回头我测试一下。

**Comment by xuhuisheng** [comment]
9.0.1汉化正常，可能是你没有把浏览器的语言设置成中心。参考这个问题https://github.com/xuhuisheng/sonar-l10n-zh/issues/9
![图片](https://user-images.githubusercontent.com/1118508/130336586-41a70315-8a6e-4a57-aec7-ec4b582088dc.png)

**Comment by zhenyu-lan** [comment]
OK，果然是这个问题，如此设置后，就显示中文了；
![image](https://user-images.githubusercontent.com/62124738/130382983-d72d0e28-009e-48da-ac89-f0a68e2abe53.png)
![image](https://user-images.githubusercontent.com/62124738/130383028-c352ddeb-e368-47df-bde6-4f51bf6aa494.png)
