### ISSUE TITLE
sonarqube-9.2.0.49834安装9.2插件后无法进入系统

### ISSUE THREAD

**Issue by lilongjie1137** [xuhuisheng/sonar-l10n-zh#49]
应用市场现在还是9.1的,安装后卡在Loding界面无法进入,删除插件后手动下载9.2插件放进去,还是同样的无限加载,打开控制台发现有这样一个报错:
![image](https://user-images.githubusercontent.com/33718778/143181717-49c7ee40-88d7-44cb-b98a-b44ec4a677a2.png)

**Comment by cddaiwei** [comment]
我也遇到此问题了。期待解决方案

**Comment by Eudonomia** [comment]
同样遇到此问题

**Comment by skTsta** [comment]
一样的问题

**Comment by xuhuisheng** [comment]
目前认为是SonarQube-9.2前端动态加载`react-intl/locale-data/zh`的问题

* <https://github.com/SonarSource/sonarqube/blob/master/server/sonar-web/src/main/js/helpers/l10n.ts#L153>
* <https://community.sonarsource.com/t/new-release-sonar-l10n-zh-plugin-9-2/53499/2>

**Comment by xiaochengyez** [comment]
这个问题什么什么时候修复？

**Comment by GodLiang** [comment]
这我就放心了。我心思我一直启动不起来呢

**Comment by xiaochengyez** [comment]
一样的问题，期待修复

**Comment by xuhuisheng** [comment]
SonarQube-9.2.1下依然是同样的问题。

已经在官方论坛发了bug，等待官方响应
<https://community.sonarsource.com/t/sonar-l10n-zh-blocking-sonarqube-9-2/53956>

**Comment by xuhuisheng** [comment]
官方终于有回应了

1. 问题应该不是出在l10n插件上，问题应该在sonarqube里边。<https://community.sonarsource.com/t/new-release-sonar-l10n-zh-plugin-9-2/53499/3?u=xuhuisheng>
2. 俄语翻译也遇到同样问题 <https://community.sonarsource.com/t/sonar-l10n-zh-blocking-sonarqube-9-2/53956/2?u=xuhuisheng>
3. 法语翻译同样问题 <https://community.sonarsource.com/t/web-interfaces-hung-in-loading-state-since-we-upgraded-from-9-1-to-9-2-1/54233> 
4. Ann已接受sonar-l10n-zh-9.2向应用市场的提交，当然现在还是用不了 <https://github.com/SonarSource/sonar-update-center-properties/pull/254>
5. Jeremy接受了论坛上的问题提交，已创建内部ticket跟进 <https://jira.sonarsource.com/browse/SONAR-15779>

**Comment by 492162921** [comment]
看到大家一样的问题， 我也就安心了。

**Comment by yuxianwen** [comment]
大家这些天先捡起那崴脚的英语吧！

**Comment by alex1987chn** [comment]
我还以为我这边安装问题，一直进不去，最后把plugin删掉，才进来。。马上来看下

**Comment by 1054522381** [comment]
> 官方终于有回应了
> 
> 1. 问题应该不是出在l10n插件上，问题应该在sonarqube里边。https://community.sonarsource.com/t/new-release-sonar-l10n-zh-plugin-9-2/53499/3?u=xuhuisheng
> 2. 俄语翻译也遇到同样问题 https://community.sonarsource.com/t/sonar-l10n-zh-blocking-sonarqube-9-2/53956/2?u=xuhuisheng
> 3. 法语翻译同样问题 https://community.sonarsource.com/t/web-interfaces-hung-in-loading-state-since-we-upgraded-from-9-1-to-9-2-1/54233
> 4. Ann已接受sonar-l10n-zh-9.2向应用市场的提交，当然现在还是用不了 [sonar-l10n-zh-9.2 SonarSource/sonar-update-center-properties#254](https://github.com/SonarSource/sonar-update-center-properties/pull/254)
> 5. Jeremy接受了论坛上的问题提交，已创建内部ticket跟进 https://jira.sonarsource.com/browse/SONAR-15779

issue状态已经fix了，不知道sonar9.3什么时候发布

**Comment by xuhuisheng** [comment]
看官方的意思，估计跟着修复log4j2一起发布8.9.4和9.2.2。期望圣诞节之前。

**Comment by xuhuisheng** [comment]
![Screenshot from 2021-12-15 10-53-10](https://user-images.githubusercontent.com/1118508/146114535-58861b48-947b-4f57-a55e-01864a5fa92c.png)

<https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.2.2.50622.zip>

9.2.2已发布，本地测试通过。
