### ISSUE TITLE
sonar9.1汉化插件不生效，页面依旧是英文

### ISSUE THREAD

**Issue by zhw0719** [xuhuisheng/sonar-l10n-zh#50]
![Snipaste_2021-12-29_08-51-13](https://user-images.githubusercontent.com/96814705/147638509-215f1fa0-6c3e-41dd-9c59-d946378e82ad.png)

**Comment by xuhuisheng** [comment]
请参考历史问题：
https://github.com/xuhuisheng/sonar-l10n-zh/issues/9
