### ISSUE TITLE
9.2放入extensions/plugins后一直loading 看到对I10n访问报304了

### ISSUE THREAD

**Issue by wyfzjy** [xuhuisheng/sonar-l10n-zh#52]
离线安装
9.2放入extensions/plugins后一直loading 看到有I10n的相关访问报了304

**Comment by xuhuisheng** [comment]
已知问题，需要把sonarqube升级至9.2.2以上版本。详情参考 https://github.com/xuhuisheng/sonar-l10n-zh/issues/49
