### ISSUE TITLE
最新Chinese Pack包在SonarQube 9.5.0.56709中没有生效

### ISSUE THREAD

**Issue by lutixiaya** [xuhuisheng/sonar-l10n-zh#54]
**SonarQube版本：**
![image](https://user-images.githubusercontent.com/48750425/176588768-e0d1b6df-95d4-4f01-b7cd-b062dacbbdbc.png)

**Chinese Pack包：**
![image](https://user-images.githubusercontent.com/48750425/176588824-f3a3a596-6919-4059-b521-1afa905ac928.png)

SonarQube重启两次，依然没有反应，不知道是什么原因？

**Comment by dark123y** [comment]
同样的问题

**Comment by xuhuisheng** [comment]
请参考历史问题:
#9

**Comment by lutixiaya** [comment]
感谢，经过设置浏览器语言，确实可以了。
