### ISSUE TITLE
sonar10安装了sonar-l10n-zh-plugin-10.0不生效，重启也不生效

### ISSUE THREAD

**Issue by jon-cao** [xuhuisheng/sonar-l10n-zh#60]
![image](https://user-images.githubusercontent.com/30084705/233888848-1ad6f7fd-05e0-45f2-9b96-3b2ae92f9b98.png)

**Comment by xuhuisheng** [comment]
请参考历史问题:
https://github.com/xuhuisheng/sonar-l10n-zh/issues/9

**Comment by jon-cao** [comment]
确实是这个问题，chrome首选语言改为中文后好了
