### ISSUE TITLE
翻译不完整，请看截图

### ISSUE THREAD

**Issue by WestFarmer** [xuhuisheng/sonar-l10n-zh#61]
![图片](https://github.com/xuhuisheng/sonar-l10n-zh/assets/14016562/48c75a5d-4c94-45e3-871b-3c8cb73aab63)

已导入，后面有个{link}

**Comment by xuhuisheng** [comment]
@WestFarmer 请提供对应版本，比如是否sonar-10.0.0。

**Comment by WestFarmer** [comment]
> 

版本为最新版， Sonar-10.0.0
