### ISSUE TITLE
兄啊,10.2更新了

### ISSUE THREAD

**Issue by mysmlz** [xuhuisheng/sonar-l10n-zh#66]
10.2更新了,又多了好多新的字符串

他那个字符串源文件从哪获取的,要不我fork一下做个机翻?

**Comment by xuhuisheng** [comment]
在sonar-core.jar里，有一个core.propertis

**Comment by xuhuisheng** [comment]
完成，等待官方上架。

<https://github.com/SonarSource/sonar-update-center-properties/pull/438>
