### ISSUE TITLE
手动导入没生效

### ISSUE THREAD

**Issue by hinata-sen** [xuhuisheng/sonar-l10n-zh#69]
我手动下载了汉化包放到了/opt/sonarqube-10.3.0.82913/extensions/plugins/目录下，用 sh sonar.sh restart命令重启了sonar，但是登录上去还是英文，是我哪里配置有问题吗？

**Comment by xuhuisheng** [comment]
参考历史问题
#9

**Comment by xuhuisheng** [comment]
两个月没有反馈，先把问题关闭，如果还有问题，可以重开。
