### ISSUE TITLE
崔更一下 10.4.1版本啊，辛苦辛苦！！

### ISSUE THREAD

**Issue by shanhm1991** [xuhuisheng/sonar-l10n-zh#72]
大佬有空更新一下版本哈，sonar已经到了10.4.1版本，使用10.4插件有一些问题

**Comment by xuhuisheng** [comment]
有一个PR改了两处，跟这个PR有关吗？
https://github.com/xuhuisheng/sonar-l10n-zh/pull/71/files

**Comment by shanhm1991** [comment]
是的，要重新打包吗

**Comment by shanhm1991** [comment]
![image](https://github.com/xuhuisheng/sonar-l10n-zh/assets/12453756/1dc95e64-e9af-4a0f-a5a7-182cb38c9adb)

打了一下10.5-snapshot，还是有些显示问题

**Comment by shanhm1991** [comment]
按照pr改了下，可以了
