### ISSUE TITLE
sonarqube企业版10.4安装该插件v10.4后在总览页面部分数据显示异常

### ISSUE THREAD

**Issue by githubiscat** [xuhuisheng/sonar-l10n-zh#74]
如图红框中所示，显示很多类似变量的语句
![sonar_plugin_issue](https://github.com/xuhuisheng/sonar-l10n-zh/assets/39004847/6d066244-3c10-4db2-bb3a-4c53a7abc15e)

**Comment by xuhuisheng** [comment]
请先参考 https://github.com/xuhuisheng/sonar-l10n-zh/pull/71

**Comment by githubiscat** [comment]
修复了我的问题
